//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Calcular/", ConfigurationName="ServiceReference1.Calcular")]
    public interface Calcular {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://Calcular/)
        [System.ServiceModel.OperationContractAttribute(Action="http://Calcular/Calcular/FatorialRequest", ReplyAction="http://Calcular/Calcular/FatorialResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Calculator.ServiceReference1.FatorialResponse Fatorial(Calculator.ServiceReference1.FatorialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fatorial", WrapperNamespace="http://Calcular/", IsWrapped=true)]
    public partial class FatorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int numero;
        
        public FatorialRequest() {
        }
        
        public FatorialRequest(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FatorialResponse", WrapperNamespace="http://Calcular/", IsWrapped=true)]
    public partial class FatorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public FatorialResponse() {
        }
        
        public FatorialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcularChannel : Calculator.ServiceReference1.Calcular, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularClient : System.ServiceModel.ClientBase<Calculator.ServiceReference1.Calcular>, Calculator.ServiceReference1.Calcular {
        
        public CalcularClient() {
        }
        
        public CalcularClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcularClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.ServiceReference1.FatorialResponse Calculator.ServiceReference1.Calcular.Fatorial(Calculator.ServiceReference1.FatorialRequest request) {
            return base.Channel.Fatorial(request);
        }
        
        public int Fatorial(int numero) {
            Calculator.ServiceReference1.FatorialRequest inValue = new Calculator.ServiceReference1.FatorialRequest();
            inValue.numero = numero;
            Calculator.ServiceReference1.FatorialResponse retVal = ((Calculator.ServiceReference1.Calcular)(this)).Fatorial(inValue);
            return retVal.@return;
        }
    }
}
